### ISSUE TITLE
Different animation with vanilla shield

### ISSUE THREAD

**Issue by linzexin022** [OroArmor/Netherite-Plus-Mod#9]
Hi there, I found another problem that the animation is quite different from vanilla shield, and here are some comparison pictures:

![2020-07-26_14 34 19](https://user-images.githubusercontent.com/59003232/88473178-82ac9000-cf4d-11ea-984a-a2be2f6d087d.png)
![2020-07-26_14 34 32](https://user-images.githubusercontent.com/59003232/88473181-86d8ad80-cf4d-11ea-8283-e2cf321da3fd.png)
![2020-07-26_14 34 44](https://user-images.githubusercontent.com/59003232/88473183-89d39e00-cf4d-11ea-8df9-c3c982dd8cd3.png)
![2020-07-26_14 34 55](https://user-images.githubusercontent.com/59003232/88473184-8b04cb00-cf4d-11ea-9951-e80fb1b54b7e.png)

When I use the netherite shield, it seems like equipping something instead of holding the shield in front of player. I also used the mod _First-person Model_ to see How I raise the shield and it's also different from the vanilla.

**Comment by OroArmor** [comment]
weird, i tested that and thought i fixed it... do you have any other mods installed?

**Comment by linzexin022** [comment]
Yes and there are a LOT of other mods that I've installed. It's likely to meet problems with other mods (Maybe I should test this mod individually). OK I tested it individually (Trinket version with the latest Fabric API) and it's still the same.

I then found another conflicting mod _Everything-is-a-hat_ that I "wear" this shield on my head slot (Why am I doing this?) and it shows like this:

![image](https://user-images.githubusercontent.com/59003232/88473460-475f9080-cf50-11ea-9668-216cccb236cf.png)

Make the contrast more obvious I'll show you pictures. In _Everything-is-a-hat_ mod, if I "wear" items it will be like this:

![image](https://user-images.githubusercontent.com/59003232/88473531-09af3780-cf51-11ea-8b2b-527aabaddc6a.png)

If I "wear" blocks it will be like this:

![image](https://user-images.githubusercontent.com/59003232/88473542-23e91580-cf51-11ea-8335-76da3fbb510f.png)

It may not be set properly when setting attributes (items, entities or blocks?) I guess.  I'm just telling you that this shield may not be in the right place when modeling, and it may be caused by other conflict mods so if it works properly you don't have to fix it. It's not a serious bug actually.

**Comment by rxay579** [comment]
Also have this issue with the shield animation while using 'netherite-plus-mod-trinkets-beta-1.1.2' version.
Vanilla shield appears normal, but the netherite shield just bobs once and appears to be in normal held position.

Tested in a new MultiMC instance with only MC 1.16.1, Fabric API v0.16, Trinkets v2.6.3, and Netherite Plus Trinkets v1.1.2.

This shows up in the log every time I use the netherite shield.
[02:14:07] [main/INFO]: [STDOUT]: used
[02:14:07] [Server thread/INFO]: [STDOUT]: used

Latest log attached in case it helps (some odd errors early in the client loading).
[latest.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/4977257/latest.log)

**Comment by rxay579** [comment]
This looks like it's fixed in the NP 1.6.1 release.  Netherite shield animates like a vanilla shield for me.
